/*  NÚMERO DE VALORES FALTANTES EN SALRIO*/

PROC MEANS DATA=SASHELP.BASEBALL NMISS;
    VAR Salary;
RUN;
/*  NÚMERO DE VALORES FALTANTES EN SALRIO*/
PROC SQL;
    SELECT COUNT(*) AS inactivos
    FROM SASHELP.BASEBALL
    WHERE Salary IS MISSING;
QUIT;

/*PROCEDIMIENTO PARA CALCULAR SALARIO PROMEDIO, MÁXIMO Y MÍNIMO CUANDO SALARIO NO SEA NULO*/
PROC SQL;
    SELECT AVG(Salary) AS salario_promedio,
           MAX(Salary) AS salario_maximo,
           MIN(Salary) AS salario_minimo
    FROM SASHELP.BASEBALL
    WHERE Salary IS NOT MISSING;
QUIT;

/*CALCULA EL SALARIO PROMEDIO Y LO AGRUPA SEGUN EL EQUIPO,
SE ORDENA EN DESCENDENTE PARA QUE EL PRIMER EQUIPO SEA EL QUE TENGA EL MAYOR SALARIO PROMEDIO*/
PROC SQL;
    SELECT Team, 
           AVG(Salary) AS salario_promedio
    FROM SASHELP.BASEBALL
    WHERE Salary IS NOT MISSING
    GROUP BY Team
    ORDER BY salario_promedio DESC;
QUIT;


/**CALCULA EL SALARIO PROMEDIO Y LO AGRUPA SEGUN EL LOS AÑOS EN LAS LIGAS MAYORES,
SE ORDENA EN DESCENDENTE PARA QUE LOS PRIMEROS AÑOS MOSTRADOS SEAN LOS QUE TENGAN EL MAYOR SALARIO PROMEDIO*/
PROC SQL;
    SELECT YrMajor, 
           AVG(Salary) AS salario_promedio
    FROM SASHELP.BASEBALL
    WHERE Salary IS NOT MISSING
    GROUP BY YrMajor
    ORDER BY salario_promedio DESC;
QUIT;

/**CREAR UNA TABLA CON EL NOMBRE SALARY_FIRST_5Y QUE SE ALMACENE EN WORK, **/
PROC SQL;
    CREATE TABLE WORK.SALARY_FIRST_5Y AS
    SELECT League, 
           YrMajor, 
           MEAN(Salary) AS salario_media, 
           STD(Salary) AS desviacion_estandar,
           COUNT(*) AS num_jugadores
    FROM SASHELP.BASEBALL
    WHERE Salary IS NOT MISSING 
          AND YrMajor <= 5  /*Solo jugadores con 5 o menos años */
    GROUP BY League, YrMajor
    ORDER BY salario_media DESC; 
QUIT;

/*PRINT IMPRIME LA TABLA, SE AÑADE UN TITULO*/
PROC PRINT DATA=WORK.SALARY_FIRST_5Y;
    TITLE "Salario Promedio de Jugadores con 5 o Menos Años en Ligas Mayores";
RUN;

